services:
- docker

env:
  global:
    - secure: "J1VqnRtlGJkXVeHw6onVOZr+S2KTV0raZYNJpfUkPzvg8G0TdPIG72exeZVFsj6Sov0khDAYy7Yov78Or8NAbj3ejyapHHkxXHRNarZA/j4ANAGfbIEBx0O2d2Hj/2IeMtK/PMpudJlTtMMGjzjVKRHJwUKm2yIGYhHOGxqcJt8Woc9fRe2cWeYwbdYqbiSzjKhEcpdF72NNpkfO/3D+z5jNmT9xZ4kkVgwkxbUwtkhZLRd4rdqxyIAxyRSHkqZmZv8Pm7nCNNZtZGOdCO89CNsDzShWExA6Juom+ivcVkqXUGpHa50RA7zrz1/mxxrJEiaP+LDWyrt05za5T6pvdgT0+9CU2vQSjkP4KtgT/Ywon7sYlenZbLYUigezHR8OedYm3gSFzD/bRY30LuN7mEur/GOyUEfV2sHuuBBtlxv7rmqqHyyJXDoK4NDZvzT96E2qjTdj1ZtI30nnRQZ1xqqZMODM1Ysbzf2syIewROGqoUuLZCETv2E97z9w+H+6/LUsMH/wFBsBF1pD1+DIPi8D4O19uQy6HkNxmiHoYDaQf74xlNItDnfQJWUVPG1kQSzcpgRfjIev3c6dezmjWh3fp6CJs9RTc5qapTuh2BK7ATVlq81bX/CSkBfF4h0yd30BwZQq/XulN79EHCuArIyLi5jW9KPcwlY0uMQnZQ4="

script:
- docker build --target test --tag todoapp-test .
- docker run todoapp-test src/tests
- docker run --env-file ./.env todoapp-test src/tests_e2e
