version: "3.8"

services:
    todolist-app:
        build: 
            context: .
            target: development
        env_file: ./.env
        ports: 
            - "5000:5000"
        volumes:
            - "./src:/todo-app/src"

